#!/usr/bin/env python3
"""
Trellis 3D Model Enhancement Tool

A command-line tool for enhancing 3D models generated by Trellis using
AI-powered texture upscaling and geometry optimization.

Usage:
    python enhance.py --input model.glb --output enhanced/
    python enhance.py --input model.glb --output enhanced/ --use-sd
    python enhance.py --input model.glb --texture-scale 4 --no-geometry
"""

import argparse
import logging
import sys
from pathlib import Path
from typing import Optional
import yaml
from tqdm import tqdm

from src.texture_enhancer import TextureEnhancer
from src.geometry_optimizer import GeometryOptimizer
from src.sd_enhancer import SDEnhancer
from src.utils import validate_file, setup_logging, ensure_dir

logger = logging.getLogger(__name__)


def load_config(config_path: str = "config/config.yaml") -> dict:
    """
    Load configuration from YAML file.
    
    Args:
        config_path: Path to configuration file
    
    Returns:
        Configuration dictionary
    """
    config_path = Path(config_path)
    
    if not config_path.exists():
        logger.warning(f"Config file not found: {config_path}, using defaults")
        return {}
    
    with open(config_path, 'r') as f:
        config = yaml.safe_load(f)
    
    logger.info(f"Configuration loaded from {config_path}")
    return config


def enhance_model(
    input_path: str,
    output_dir: str,
    texture_scale: Optional[int] = None,
    enable_geometry: bool = True,
    use_sd: bool = False,
    config: Optional[dict] = None
) -> str:
    """
    Enhance a 3D model with texture upscaling and geometry optimization.
    
    Args:
        input_path: Path to input 3D model
        output_dir: Directory for output files
        texture_scale: Texture upscaling factor (overrides config)
        enable_geometry: Whether to optimize geometry
        use_sd: Whether to use Stable Diffusion enhancement
        config: Configuration dictionary
    
    Returns:
        Path to enhanced model
    """
    if config is None:
        config = {}
    
    input_path = Path(input_path)
    output_dir = Path(output_dir)
    ensure_dir(output_dir)
    
    # Validate input file
    try:
        validate_file(str(input_path), allowed_extensions=['.glb', '.obj'])
    except Exception as e:
        logger.error(f"Input validation failed: {e}")
        raise
    
    logger.info(f"Starting enhancement for: {input_path}")
    logger.info(f"Output directory: {output_dir}")
    
    # Get configuration values
    texture_config = config.get('texture', {})
    geometry_config = config.get('geometry', {})
    sd_config = config.get('sd_enhancement', {})
    output_config = config.get('output', {})
    
    # Determine texture scale
    if texture_scale is None:
        texture_scale = texture_config.get('upscale_factor', 4)
    
    # Create backup if configured
    if output_config.get('create_backup', True):
        backup_path = output_dir / f"{input_path.stem}_original{input_path.suffix}"
        import shutil
        shutil.copy(input_path, backup_path)
        logger.info(f"Original file backed up to: {backup_path}")
    
    current_file = str(input_path)
    
    # Step 1: Texture Enhancement
    logger.info("=" * 60)
    logger.info("STEP 1: Texture Enhancement")
    logger.info("=" * 60)
    
    try:
        if use_sd and sd_config.get('enable', False):
            logger.info("Using Stable Diffusion for texture enhancement")
            
            # Initialize SD enhancer
            sd_enhancer = SDEnhancer(
                model_id=sd_config.get('model', 'lllyasviel/control_v11f1e_sd15_tile'),
                use_fp16=texture_config.get('use_fp16', True)
            )
            
            if sd_enhancer.is_available():
                # Extract texture, enhance with SD, apply back
                from src.utils import extract_texture_from_mesh, apply_texture_to_mesh
                from PIL import Image
                
                texture_path = extract_texture_from_mesh(current_file, output_dir=str(output_dir / "temp"))
                if texture_path:
                    texture_img = Image.open(texture_path)
                    enhanced_texture = sd_enhancer.enhance_texture(
                        texture_img,
                        prompt=sd_config.get('prompt', 'highly detailed texture'),
                        negative_prompt=sd_config.get('negative_prompt', 'blurry, low quality'),
                        steps=sd_config.get('steps', 20),
                        conditioning_scale=sd_config.get('conditioning_scale', 0.7)
                    )
                    
                    enhanced_texture_path = output_dir / f"{input_path.stem}_texture_sd.png"
                    enhanced_texture.save(enhanced_texture_path)
                    
                    current_file = str(output_dir / f"{input_path.stem}_sd{input_path.suffix}")
                    apply_texture_to_mesh(str(input_path), str(enhanced_texture_path), current_file)
                    
                    logger.info(f"SD-enhanced model saved to: {current_file}")
                else:
                    logger.warning("No texture found, skipping SD enhancement")
            else:
                logger.warning("SD enhancer not available, falling back to Real-ESRGAN")
                use_sd = False
        
        if not use_sd:
            logger.info("Using Real-ESRGAN for texture enhancement")
            
            # Initialize texture enhancer
            texture_enhancer = TextureEnhancer(
                scale=texture_scale,
                tile_size=texture_config.get('tile_size', 1024),
                use_fp16=texture_config.get('use_fp16', True),
                weights_url=texture_config.get('weights_url')
            )
            
            # Enhance texture
            texture_output_dir = output_dir / "texture_enhanced"
            current_file = texture_enhancer.enhance_model(
                current_file,
                str(texture_output_dir),
                upscale_factor=texture_scale,
                save_texture=output_config.get('save_intermediate', False)
            )
            
            logger.info(f"Texture-enhanced model saved to: {current_file}")
    
    except Exception as e:
        logger.error(f"Texture enhancement failed: {e}")
        logger.warning("Continuing with original model")
        current_file = str(input_path)
    
    # Step 2: Geometry Optimization (if enabled)
    if enable_geometry:
        logger.info("=" * 60)
        logger.info("STEP 2: Geometry Optimization")
        logger.info("=" * 60)
        
        try:
            # Initialize geometry optimizer
            geometry_optimizer = GeometryOptimizer(
                enable_subdivision=geometry_config.get('enable_subdivision', False),
                subdivision_iterations=geometry_config.get('subdivision_iterations', 1),
                subdivision_threshold=geometry_config.get('subdivision_threshold', 1.0),
                enable_smoothing=geometry_config.get('enable_smoothing', False),
                smoothing_steps=geometry_config.get('smoothing_steps', 1)
            )
            
            # Optimize geometry
            final_output = str(output_dir / f"{input_path.stem}_enhanced{input_path.suffix}")
            current_file = geometry_optimizer.optimize_mesh(
                current_file,
                final_output,
                create_backup=False  # Already created backup earlier
            )
            
            logger.info(f"Geometry-optimized model saved to: {current_file}")
        
        except Exception as e:
            logger.error(f"Geometry optimization failed: {e}")
            logger.warning("Using texture-enhanced model as final output")
            final_output = str(output_dir / f"{input_path.stem}_enhanced{input_path.suffix}")
            import shutil
            shutil.copy(current_file, final_output)
            current_file = final_output
    else:
        logger.info("Geometry optimization disabled")
        final_output = str(output_dir / f"{input_path.stem}_enhanced{input_path.suffix}")
        if current_file != final_output:
            import shutil
            shutil.copy(current_file, final_output)
            current_file = final_output
    
    logger.info("=" * 60)
    logger.info("Enhancement Complete!")
    logger.info("=" * 60)
    logger.info(f"Enhanced model: {current_file}")
    
    return current_file


def main():
    """Main entry point for the CLI tool."""
    parser = argparse.ArgumentParser(
        description="Trellis 3D Model Enhancement Tool - Enhance 3D models with AI-powered texture upscaling",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic enhancement with 4x texture upscaling
  python enhance.py --input model.glb --output enhanced/
  
  # 2x texture upscaling with geometry optimization disabled
  python enhance.py --input model.glb --output enhanced/ --texture-scale 2 --no-geometry
  
  # Use Stable Diffusion for texture enhancement (slower but more detailed)
  python enhance.py --input model.glb --output enhanced/ --use-sd
  
  # Custom configuration file
  python enhance.py --input model.glb --output enhanced/ --config my_config.yaml
        """
    )
    
    parser.add_argument(
        '--input', '-i',
        type=str,
        required=True,
        help='Path to input 3D model (.glb or .obj)'
    )
    
    parser.add_argument(
        '--output', '-o',
        type=str,
        required=True,
        help='Output directory for enhanced model'
    )
    
    parser.add_argument(
        '--texture-scale',
        type=int,
        choices=[2, 4],
        help='Texture upscaling factor (2 or 4, default: from config or 4)'
    )
    
    parser.add_argument(
        '--no-geometry',
        action='store_true',
        help='Disable geometry optimization (only enhance textures)'
    )
    
    parser.add_argument(
        '--use-sd',
        action='store_true',
        help='Use Stable Diffusion ControlNet for texture enhancement (slower)'
    )
    
    parser.add_argument(
        '--config', '-c',
        type=str,
        default='config/config.yaml',
        help='Path to configuration file (default: config/config.yaml)'
    )
    
    parser.add_argument(
        '--log-level',
        type=str,
        choices=['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'],
        help='Logging level (default: from config or INFO)'
    )
    
    parser.add_argument(
        '--version',
        action='version',
        version='Trellis 3D Enhancement Tool v1.0.0'
    )
    
    args = parser.parse_args()
    
    # Load configuration
    config = load_config(args.config)
    
    # Setup logging
    log_config = config.get('logging', {})
    log_level_str = args.log_level or log_config.get('level', 'INFO')
    log_level = getattr(logging, log_level_str)
    log_file = log_config.get('log_file')
    
    setup_logging(log_file=log_file, level=log_level)
    
    logger.info("Trellis 3D Model Enhancement Tool v1.0.0")
    logger.info("=" * 60)
    
    try:
        # Run enhancement
        enhanced_path = enhance_model(
            input_path=args.input,
            output_dir=args.output,
            texture_scale=args.texture_scale,
            enable_geometry=not args.no_geometry,
            use_sd=args.use_sd,
            config=config
        )
        
        print("\n" + "=" * 60)
        print("✓ Enhancement completed successfully!")
        print(f"✓ Enhanced model saved to: {enhanced_path}")
        print("=" * 60)
        
        return 0
    
    except KeyboardInterrupt:
        logger.warning("Enhancement interrupted by user")
        print("\n⚠ Enhancement cancelled by user")
        return 130
    
    except Exception as e:
        logger.error(f"Enhancement failed: {e}", exc_info=True)
        print(f"\n✗ Error: {e}")
        print("Check the log file for details")
        return 1


if __name__ == '__main__':
    sys.exit(main())
