"""
Trellis 3D Model Enhancement Tool

A comprehensive toolkit for enhancing 3D models generated by Trellis using
AI-powered texture upscaling and geometry optimization.
"""

__version__ = "1.0.0"
__author__ = "Trellis 3D Enhancement Team"

from .texture_enhancer import TextureEnhancer
from .geometry_optimizer import GeometryOptimizer
from .sd_enhancer import SDEnhancer
from .utils import (
    extract_texture_from_mesh,
    apply_texture_to_mesh,
    download_file,
    validate_file,
)

__all__ = [
    "TextureEnhancer",
    "GeometryOptimizer",
    "SDEnhancer",
    "extract_texture_from_mesh",
    "apply_texture_to_mesh",
    "download_file",
    "validate_file",
]
